/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.11.4
// source: proto/client.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_client_pb from '../proto/client_pb';


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorgetWordlist = new grpcWeb.MethodDescriptor(
    '/UserService/getWordlist',
    grpcWeb.MethodType.UNARY,
    proto_client_pb.Empty,
    proto_client_pb.wordlist,
    (request: proto_client_pb.Empty) => {
      return request.serializeBinary();
    },
    proto_client_pb.wordlist.deserializeBinary
  );

  getWordlist(
    request: proto_client_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<proto_client_pb.wordlist>;

  getWordlist(
    request: proto_client_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_client_pb.wordlist) => void): grpcWeb.ClientReadableStream<proto_client_pb.wordlist>;

  getWordlist(
    request: proto_client_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_client_pb.wordlist) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/UserService/getWordlist',
        request,
        metadata || {},
        this.methodDescriptorgetWordlist,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/UserService/getWordlist',
    request,
    metadata || {},
    this.methodDescriptorgetWordlist);
  }

  methodDescriptoraddNewWordlist = new grpcWeb.MethodDescriptor(
    '/UserService/addNewWordlist',
    grpcWeb.MethodType.UNARY,
    proto_client_pb.wordlist,
    proto_client_pb.Response,
    (request: proto_client_pb.wordlist) => {
      return request.serializeBinary();
    },
    proto_client_pb.Response.deserializeBinary
  );

  addNewWordlist(
    request: proto_client_pb.wordlist,
    metadata: grpcWeb.Metadata | null): Promise<proto_client_pb.Response>;

  addNewWordlist(
    request: proto_client_pb.wordlist,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_client_pb.Response) => void): grpcWeb.ClientReadableStream<proto_client_pb.Response>;

  addNewWordlist(
    request: proto_client_pb.wordlist,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_client_pb.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/UserService/addNewWordlist',
        request,
        metadata || {},
        this.methodDescriptoraddNewWordlist,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/UserService/addNewWordlist',
    request,
    metadata || {},
    this.methodDescriptoraddNewWordlist);
  }

}

