projects:
  lingologin:
    schemaPath: src/graphql/schema.json
    includes:
      - loginApi
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
