env:
  browser: true
  es2021: true
<<<<<<< Updated upstream
=======
  jest: true
>>>>>>> Stashed changes
extends: standard
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
