name: GameService code updated

on:
  push:
    branches: ["Development", "master"]
    paths:
      - "BackEnd/Services/GameService/**.js"

env:
  IMAGE_NAME: gameservice
  REPO_NAME: jurrewolff

jobs:
  test:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
      working-directory: ./BackEnd/Services/GameService

    - run: npm test
      working-directory: ./BackEnd/Services/GameService

  push:

    needs: test

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build docker
      run: docker build . -t $REPO_NAME/$IMAGE_NAME
      working-directory: ./BackEnd/Services/GameService

    - name: Push image to docker hub Container Registry
      run: docker push $REPO_NAME/$IMAGE_NAME
      working-directory: ./BackEnd/Services/GameService
